### ISSUE TITLE
SSH Keys

### ISSUE THREAD

**Issue by duduws** [HotNoob/Oracle-Free-Arm-VPS-PS#3]
if the script was succefull in create a new instance, where can i find ssh keys? or there is any way to create the ssh keys after the creation of the instance?

**Comment by HotNoob** [comment]
been a while, but the default password is blank. default username is ubuntu for me. 

to get in the first time, i think you goto on the webui, to the instance -> instance details -> console connection -> launch cloud connection

and then you should be able to login with a blank password, and setup everything how you like it.

**Comment by duduws** [comment]
> been a while, but the default password is blank. default username is ubuntu for me.
> 
> to get in the first time, i think you goto on the webui, to the instance -> instance details -> console connection -> launch cloud connection
> 
> and then you should be able to login with a blank password, and setup everything how you like it.

thank you for the fast reply, but im trying to figure out how can i use this instance to connect via "Putty"/ssh, cause the script is running right now, but if they create the instance, i wish they can create a .pem file for me to use in putty for ssh connections too like the other scripts, i really like you script cause it uses windows power shell.

**Comment by HotNoob** [comment]
once connected in cloud shell thing, just slap your ssh pub key into ~/.ssh/authorized_keys

setting a password should also let you ssh in.

**Comment by HotNoob** [comment]
if you havent gotten your instance yet. you can add it in:

add this to the end of line 108: https://github.com/HotNoob/Oracle-Free-Arm-VPS-PS/blob/63d9cdbcf4dae77aa5edbb8b9a55058bcdabaeee/create_oracle_arm_instance.ps1#L108

--metadata `"{`'ssh_authorized_keys`':`'YOUR SSH KEY HERE`'}`"
or
--ssh-authorized-keys-file {FILE NAME FOR YOUR authorized_keys content }

**Comment by duduws** [comment]
> if you havent gotten your instance yet. you can add it in:
> 
> add this to the end of line 108 just before " 2>&1 ":
> 
> https://github.com/HotNoob/Oracle-Free-Arm-VPS-PS/blob/63d9cdbcf4dae77aa5edbb8b9a55058bcdabaeee/create_oracle_arm_instance.ps1#L108
> 
> --metadata `"{`'ssh_authorized_keys`':`'YOUR SSH KEY HERE`'}`" or --ssh-authorized-keys-file {FILE NAME FOR YOUR authorized_keys content }

my line 108 its like this, should be right?

`    $response = & iex "& oci compute instance launch --no-retry --availability-domain $availDomain $authParams --compartment-id $tenancyId --image-id $imageId  --shape 'VM.Standard.A1.Flex' --shape-config `"{`'ocpus`':$cpus,`'memoryInGBs`':$ram}`"  --subnet-id $subnetId --metadata "{'ssh_authorized_keys':'ssh-rsa AAAAB3NzaC1yc2.......'}" " 2>&1`

**Comment by F-alling** [comment]
> if you havent gotten your instance yet. you can add it in:
> 
> add this to the end of line 108 just before " 2>&1 ":
> 
> https://github.com/HotNoob/Oracle-Free-Arm-VPS-PS/blob/63d9cdbcf4dae77aa5edbb8b9a55058bcdabaeee/create_oracle_arm_instance.ps1#L108
> 
> --metadata `"{`'ssh_authorized_keys`':`'YOUR SSH KEY HERE`'}`" or --ssh-authorized-keys-file {FILE NAME FOR YOUR authorized_keys content }

Would I do `--metadata "{'ssh_authorized_keys':'YOUR SSH KEY HERE'}"` with  the path for it, or put the SSH key in the same directory as the script?

**Comment by HotNoob** [comment]
for least confusion, i'd just put the full absolute path in, otherwise i think the base path would be the cwd; so where ever you execute the script or where the script is. not 100% certain on powershells cwd behaviour.

**Comment by F-alling** [comment]
and I know this is a noob question but would I put the public key or private?

**Comment by HotNoob** [comment]
public key.

**Comment by F-alling** [comment]
k

**Comment by F-alling** [comment]
Put the argument in and I get.
`nvoke-Expression : A positional parameter cannot be found that accepts argument '--metadata'.
At V:\oracle\create_oracle_arm_instance.ps1:108 char:17
+ ... $response = & iex "& oci compute instance launch --no-retry --availab ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-Expression], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.InvokeExpressionCommand

RESPONSE:
ConvertFrom-Json : Cannot bind argument to parameter 'InputObject' because it is null.
At V:\oracle\create_oracle_arm_instance.ps1:119 char:33
+             $json = $response | ConvertFrom-Json
+                                 ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertFrom-Json], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

JSON :
1 of 1440 - 05/17/2024 09:57:41
Invoke-Expression : A positional parameter cannot be found that accepts argument '--metadata'.
At V:\oracle\create_oracle_arm_instance.ps1:108 char:17
+ ... $response = & iex "& oci compute instance launch --no-retry --availab ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-Expression], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.InvokeExpressionCommand

RESPONSE:
ConvertFrom-Json : Cannot bind argument to parameter 'InputObject' because it is null.
At V:\oracle\create_oracle_arm_instance.ps1:119 char:33
+             $json = $response | ConvertFrom-Json
+                                 ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertFrom-Json], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ConvertFromJsonCommand`

**Comment by F-alling** [comment]
@HotNoob

**Comment by F-alling** [comment]
> public key.
https://github.com/HotNoob/Oracle-Free-Arm-VPS-PS/issues/3#issuecomment-2117791607

**Comment by HotNoob** [comment]
likely to be a syntax error. pay attention to all of the ` and ", github fails at parsing those, so they will be wrong in the code blocks ect...

**Comment by TuBui** [comment]
> been a while, but the default password is blank. default username is ubuntu for me.
> 
> to get in the first time, i think you goto on the webui, to the instance -> instance details -> console connection -> launch cloud connection
> 
> and then you should be able to login with a blank password, and setup everything how you like it.

I was able to create a running instance using the default settings but couldn't access the machine. Launching a cloud shell with username ubuntu and blank password doesn't get me in (got **Login incorrect** error). Too bad I didn't read this thread about enclosing the ssh pubkey in the `oci compute instance launch` command. It takes me very long time to get this instance, is there a way to login to add a custom pub key, other than deleting the instance and try my luck again?

**Comment by HotNoob** [comment]
> > been a while, but the default password is blank. default username is ubuntu for me.
> > to get in the first time, i think you goto on the webui, to the instance -> instance details -> console connection -> launch cloud connection
> > and then you should be able to login with a blank password, and setup everything how you like it.
> 
> I was able to create a running instance using the default settings but couldn't access the machine. Launching a cloud shell with username ubuntu and blank password doesn't get me in (got **Login incorrect** error). Too bad I didn't read this thread about enclosing the ssh pubkey in the `oci compute instance launch` command. It takes me very long time to get this instance, is there a way to login to add a custom pub key, other than deleting the instance and try my luck again?

it should be the default login. 
the default login depends on what os you chose. 

username is opc for centos or oracle linux, ubuntu for ubuntu
pass is empty

**Comment by F-alling** [comment]
> likely to be a syntax error. pay attention to all of the ` and ", github fails at parsing those, so they will be wrong in the code blocks ect...

@HotNoob  I still cant get it to run even with changing all syntaxs

**Comment by HotNoob** [comment]
i added an update to the script so you can just put the key in a variable. 
power shell's syntax is... a bit troublesome when your used to other languages.
